// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package store

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createBlogStmt, err = db.PrepareContext(ctx, createBlog); err != nil {
		return nil, fmt.Errorf("error preparing query CreateBlog: %w", err)
	}
	if q.createUserStmt, err = db.PrepareContext(ctx, createUser); err != nil {
		return nil, fmt.Errorf("error preparing query CreateUser: %w", err)
	}
	if q.createUserProfileStmt, err = db.PrepareContext(ctx, createUserProfile); err != nil {
		return nil, fmt.Errorf("error preparing query CreateUserProfile: %w", err)
	}
	if q.deleteBlogStmt, err = db.PrepareContext(ctx, deleteBlog); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteBlog: %w", err)
	}
	if q.deleteUserStmt, err = db.PrepareContext(ctx, deleteUser); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteUser: %w", err)
	}
	if q.getBlogStmt, err = db.PrepareContext(ctx, getBlog); err != nil {
		return nil, fmt.Errorf("error preparing query GetBlog: %w", err)
	}
	if q.getTotalUsersCountStmt, err = db.PrepareContext(ctx, getTotalUsersCount); err != nil {
		return nil, fmt.Errorf("error preparing query GetTotalUsersCount: %w", err)
	}
	if q.getUserStmt, err = db.PrepareContext(ctx, getUser); err != nil {
		return nil, fmt.Errorf("error preparing query GetUser: %w", err)
	}
	if q.getUserByUsernameOrEmailStmt, err = db.PrepareContext(ctx, getUserByUsernameOrEmail); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByUsernameOrEmail: %w", err)
	}
	if q.getUserProfileByUserIdStmt, err = db.PrepareContext(ctx, getUserProfileByUserId); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserProfileByUserId: %w", err)
	}
	if q.listBlogsStmt, err = db.PrepareContext(ctx, listBlogs); err != nil {
		return nil, fmt.Errorf("error preparing query ListBlogs: %w", err)
	}
	if q.listUsersStmt, err = db.PrepareContext(ctx, listUsers); err != nil {
		return nil, fmt.Errorf("error preparing query ListUsers: %w", err)
	}
	if q.updateBlogStmt, err = db.PrepareContext(ctx, updateBlog); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateBlog: %w", err)
	}
	if q.updateUserStmt, err = db.PrepareContext(ctx, updateUser); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUser: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createBlogStmt != nil {
		if cerr := q.createBlogStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createBlogStmt: %w", cerr)
		}
	}
	if q.createUserStmt != nil {
		if cerr := q.createUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createUserStmt: %w", cerr)
		}
	}
	if q.createUserProfileStmt != nil {
		if cerr := q.createUserProfileStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createUserProfileStmt: %w", cerr)
		}
	}
	if q.deleteBlogStmt != nil {
		if cerr := q.deleteBlogStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteBlogStmt: %w", cerr)
		}
	}
	if q.deleteUserStmt != nil {
		if cerr := q.deleteUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteUserStmt: %w", cerr)
		}
	}
	if q.getBlogStmt != nil {
		if cerr := q.getBlogStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getBlogStmt: %w", cerr)
		}
	}
	if q.getTotalUsersCountStmt != nil {
		if cerr := q.getTotalUsersCountStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTotalUsersCountStmt: %w", cerr)
		}
	}
	if q.getUserStmt != nil {
		if cerr := q.getUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserStmt: %w", cerr)
		}
	}
	if q.getUserByUsernameOrEmailStmt != nil {
		if cerr := q.getUserByUsernameOrEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByUsernameOrEmailStmt: %w", cerr)
		}
	}
	if q.getUserProfileByUserIdStmt != nil {
		if cerr := q.getUserProfileByUserIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserProfileByUserIdStmt: %w", cerr)
		}
	}
	if q.listBlogsStmt != nil {
		if cerr := q.listBlogsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listBlogsStmt: %w", cerr)
		}
	}
	if q.listUsersStmt != nil {
		if cerr := q.listUsersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listUsersStmt: %w", cerr)
		}
	}
	if q.updateBlogStmt != nil {
		if cerr := q.updateBlogStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateBlogStmt: %w", cerr)
		}
	}
	if q.updateUserStmt != nil {
		if cerr := q.updateUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                           DBTX
	tx                           *sql.Tx
	createBlogStmt               *sql.Stmt
	createUserStmt               *sql.Stmt
	createUserProfileStmt        *sql.Stmt
	deleteBlogStmt               *sql.Stmt
	deleteUserStmt               *sql.Stmt
	getBlogStmt                  *sql.Stmt
	getTotalUsersCountStmt       *sql.Stmt
	getUserStmt                  *sql.Stmt
	getUserByUsernameOrEmailStmt *sql.Stmt
	getUserProfileByUserIdStmt   *sql.Stmt
	listBlogsStmt                *sql.Stmt
	listUsersStmt                *sql.Stmt
	updateBlogStmt               *sql.Stmt
	updateUserStmt               *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                           tx,
		tx:                           tx,
		createBlogStmt:               q.createBlogStmt,
		createUserStmt:               q.createUserStmt,
		createUserProfileStmt:        q.createUserProfileStmt,
		deleteBlogStmt:               q.deleteBlogStmt,
		deleteUserStmt:               q.deleteUserStmt,
		getBlogStmt:                  q.getBlogStmt,
		getTotalUsersCountStmt:       q.getTotalUsersCountStmt,
		getUserStmt:                  q.getUserStmt,
		getUserByUsernameOrEmailStmt: q.getUserByUsernameOrEmailStmt,
		getUserProfileByUserIdStmt:   q.getUserProfileByUserIdStmt,
		listBlogsStmt:                q.listBlogsStmt,
		listUsersStmt:                q.listUsersStmt,
		updateBlogStmt:               q.updateBlogStmt,
		updateUserStmt:               q.updateUserStmt,
	}
}
