// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package store

import (
	"context"
	"database/sql"
)

const createBlog = `-- name: CreateBlog :one

INSERT INTO blogs (title, content, user_id, created, updated)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, title, content, user_id, created, updated
`

type CreateBlogParams struct {
	Title   string       `json:"title"`
	Content string       `json:"content"`
	UserID  int32        `json:"user_id"`
	Created sql.NullTime `json:"created"`
	Updated sql.NullTime `json:"updated"`
}

// You can use RETURNING to get the id of the deleted row (optional)
func (q *Queries) CreateBlog(ctx context.Context, arg CreateBlogParams) (Blog, error) {
	row := q.queryRow(ctx, q.createBlogStmt, createBlog,
		arg.Title,
		arg.Content,
		arg.UserID,
		arg.Created,
		arg.Updated,
	)
	var i Blog
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.UserID,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email, password, created, updated)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, username, email, created, updated
`

type CreateUserParams struct {
	Username string       `json:"username"`
	Email    string       `json:"email"`
	Password string       `json:"password"`
	Created  sql.NullTime `json:"created"`
	Updated  sql.NullTime `json:"updated"`
}

type CreateUserRow struct {
	ID       int32        `json:"id"`
	Username string       `json:"username"`
	Email    string       `json:"email"`
	Created  sql.NullTime `json:"created"`
	Updated  sql.NullTime `json:"updated"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.queryRow(ctx, q.createUserStmt, createUser,
		arg.Username,
		arg.Email,
		arg.Password,
		arg.Created,
		arg.Updated,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const createUserProfile = `-- name: CreateUserProfile :one
INSERT INTO user_profiles (user_id, profile_image)
VALUES ($1, $2)
RETURNING id, user_id, profile_image
`

type CreateUserProfileParams struct {
	UserID       int32          `json:"user_id"`
	ProfileImage sql.NullString `json:"profile_image"`
}

type CreateUserProfileRow struct {
	ID           int32          `json:"id"`
	UserID       int32          `json:"user_id"`
	ProfileImage sql.NullString `json:"profile_image"`
}

func (q *Queries) CreateUserProfile(ctx context.Context, arg CreateUserProfileParams) (CreateUserProfileRow, error) {
	row := q.queryRow(ctx, q.createUserProfileStmt, createUserProfile, arg.UserID, arg.ProfileImage)
	var i CreateUserProfileRow
	err := row.Scan(&i.ID, &i.UserID, &i.ProfileImage)
	return i, err
}

const deleteBlog = `-- name: DeleteBlog :exec
DELETE FROM blogs
WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteBlog(ctx context.Context, id int32) error {
	_, err := q.exec(ctx, q.deleteBlogStmt, deleteBlog, id)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.exec(ctx, q.deleteUserStmt, deleteUser, id)
	return err
}

const getBlog = `-- name: GetBlog :one
SELECT id, title, content, user_id, created, updated
FROM blogs
WHERE id = $1
`

func (q *Queries) GetBlog(ctx context.Context, id int32) (Blog, error) {
	row := q.queryRow(ctx, q.getBlogStmt, getBlog, id)
	var i Blog
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.UserID,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const getTotalUsersCount = `-- name: GetTotalUsersCount :one

SELECT COUNT(*) AS total FROM users
`

// You can use RETURNING to get the id of the deleted row (optional)
func (q *Queries) GetTotalUsersCount(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.getTotalUsersCountStmt, getTotalUsersCount)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const getUser = `-- name: GetUser :one
SELECT id, username, email, created, updated
FROM users
WHERE id = $1
`

type GetUserRow struct {
	ID       int32        `json:"id"`
	Username string       `json:"username"`
	Email    string       `json:"email"`
	Created  sql.NullTime `json:"created"`
	Updated  sql.NullTime `json:"updated"`
}

func (q *Queries) GetUser(ctx context.Context, id int32) (GetUserRow, error) {
	row := q.queryRow(ctx, q.getUserStmt, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const getUserByUsernameOrEmail = `-- name: GetUserByUsernameOrEmail :one
SELECT id, username, email, created, updated, password
FROM users
WHERE username = $1 OR email = $1
`

type GetUserByUsernameOrEmailRow struct {
	ID       int32        `json:"id"`
	Username string       `json:"username"`
	Email    string       `json:"email"`
	Created  sql.NullTime `json:"created"`
	Updated  sql.NullTime `json:"updated"`
	Password string       `json:"password"`
}

func (q *Queries) GetUserByUsernameOrEmail(ctx context.Context, username string) (GetUserByUsernameOrEmailRow, error) {
	row := q.queryRow(ctx, q.getUserByUsernameOrEmailStmt, getUserByUsernameOrEmail, username)
	var i GetUserByUsernameOrEmailRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Created,
		&i.Updated,
		&i.Password,
	)
	return i, err
}

const getUserProfileByUserId = `-- name: GetUserProfileByUserId :one
SELECT id, user_id, profile_image, created, updated
FROM user_profiles
WHERE user_id = $1
`

func (q *Queries) GetUserProfileByUserId(ctx context.Context, userID int32) (UserProfile, error) {
	row := q.queryRow(ctx, q.getUserProfileByUserIdStmt, getUserProfileByUserId, userID)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProfileImage,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const listBlogs = `-- name: ListBlogs :many
SELECT id, title, content, user_id, created, updated
FROM blogs
ORDER BY id
LIMIT $1 OFFSET $2
`

type ListBlogsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListBlogs(ctx context.Context, arg ListBlogsParams) ([]Blog, error) {
	rows, err := q.query(ctx, q.listBlogsStmt, listBlogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Blog{}
	for rows.Next() {
		var i Blog
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.UserID,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, email, created, updated
FROM users
ORDER BY id
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListUsersRow struct {
	ID       int32        `json:"id"`
	Username string       `json:"username"`
	Email    string       `json:"email"`
	Created  sql.NullTime `json:"created"`
	Updated  sql.NullTime `json:"updated"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.query(ctx, q.listUsersStmt, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBlog = `-- name: UpdateBlog :one
UPDATE blogs
SET title = $1, content = $2, user_id = $3, updated = $4
WHERE id = $5
RETURNING id, title, content, user_id, created, updated
`

type UpdateBlogParams struct {
	Title   string       `json:"title"`
	Content string       `json:"content"`
	UserID  int32        `json:"user_id"`
	Updated sql.NullTime `json:"updated"`
	ID      int32        `json:"id"`
}

func (q *Queries) UpdateBlog(ctx context.Context, arg UpdateBlogParams) (Blog, error) {
	row := q.queryRow(ctx, q.updateBlogStmt, updateBlog,
		arg.Title,
		arg.Content,
		arg.UserID,
		arg.Updated,
		arg.ID,
	)
	var i Blog
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.UserID,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET username = $1, email = $2, password = $3, updated = $4
WHERE id = $5
RETURNING id, username, email, created, updated
`

type UpdateUserParams struct {
	Username string       `json:"username"`
	Email    string       `json:"email"`
	Password string       `json:"password"`
	Updated  sql.NullTime `json:"updated"`
	ID       int32        `json:"id"`
}

type UpdateUserRow struct {
	ID       int32        `json:"id"`
	Username string       `json:"username"`
	Email    string       `json:"email"`
	Created  sql.NullTime `json:"created"`
	Updated  sql.NullTime `json:"updated"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.queryRow(ctx, q.updateUserStmt, updateUser,
		arg.Username,
		arg.Email,
		arg.Password,
		arg.Updated,
		arg.ID,
	)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Created,
		&i.Updated,
	)
	return i, err
}
